-- Generated by fetch_product_images.py. Run in the Supabase SQL Editor.

update public.products set image_url = '/products/arduino-uno-r3-compatible-board.jpg' where slug = 'arduino-uno-r3-compatible-board';
update public.products set image_url = '/products/esp32-devkit-v1.jpg' where slug = 'esp32-devkit-v1';
update public.products set image_url = '/products/breadboard-830-points.jpg' where slug = 'breadboard-830-points';
update public.products set image_url = '/products/jumper-wire-set-120-pieces.jpg' where slug = 'jumper-wire-set-120-pieces';
update public.products set image_url = '/products/resistor-kit-600-pieces.jpg' where slug = 'resistor-kit-600-pieces';
update public.products set image_url = '/products/capacitor-kit-300-pieces.jpg' where slug = 'capacitor-kit-300-pieces';
update public.products set image_url = '/products/led-kit-300-pieces.jpg' where slug = 'led-kit-300-pieces';
update public.products set image_url = '/products/ne555-timer-ic-pack-of-10.jpg' where slug = 'ne555-timer-ic-pack-of-10';
update public.products set image_url = '/products/soldering-iron-60-w-adjustable.jpg' where slug = 'soldering-iron-60-w-adjustable';
update public.products set image_url = '/products/digital-multimeter.jpg' where slug = 'digital-multimeter';
update public.products set image_url = '/products/hc-sr04-ultrasonic-sensor.jpg' where slug = 'hc-sr04-ultrasonic-sensor';
update public.products set image_url = '/products/sg90-micro-servo.jpg' where slug = 'sg90-micro-servo';
